version: '3'
services:
  geth:
    image: ethereum/client-go
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    entrypoint:
      - geth
      - --syncmode=snap
      - --verbosity=3
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=web3,debug,eth,txpool,net,engine,admin
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=debug,eth,txpool,net,engine
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --metrics 
      - --metrics.addr=127.0.0.1
      - --metrics.expensive
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ${GETH_DATADIR-./data/geth}:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: [ "CMD-SHELL", "geth attach --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    pull_policy: always
    container_name: prysm
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - ${PRYSM_DATADIR:-./data/prysm}:/data
      - ${GETH_DATADIR:-./data/geth}:/geth
    depends_on:
      geth:
        condition: service_healthy
    ports:
      - 4000:4000
      - 13000:13000
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --checkpoint-sync-url=https://sync-mainnet.beaconcha.in
      - --genesis-beacon-api-url=https://sync-mainnet.beaconcha.in
      - --min-sync-peers=7
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/geth/jwt.hex
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --grpc-gateway-corsdomain=*
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=13000
