global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- 'record.geth.rules.yml'

scrape_configs:
- job_name: 'geth'
  scrape_interval: 10s
  metrics_path: '/debug/metrics/prometheus'
  static_configs:
  - targets:
    - 'geth:6060'
    labels:
      chain: ethereum
- job_name: 'beacon node'
  static_configs:
  - targets: ['beacon:8080']
- job_name: 'validator'
  static_configs:
  - targets: ['localhost:8081']
- job_name: 'slasher'
  static_configs:
  - targets: ['localhost:8082']
